class AnalysisTool {
  final String id, section, title, subtitle, units, formula, intuition, rigor;
  const AnalysisTool(
    this.id,
    this.section,
    this.title,
    this.subtitle,
    this.units,
    this.formula,
    this.intuition,
    this.rigor,
  );
}

const tools = <AnalysisTool>[
  AnalysisTool(
    'waveform',
    'Signal',
    'Waveform',
    'Pressure, sampled in time',
    'normalized amplitude',
    'tₙ = n / fₛ\nx[n] ∈ [−1, 1]',
    'A recording is a very fast diary of air pressure. Zoom in and the music becomes a sequence of numbers.',
    'Samples are mono floating-point PCM. Amplitude is relative to digital full scale, not calibrated sound pressure. Imported channels are averaged; opposite-phase stereo can cancel. The waveform display averages five neighboring 64-sample min/max envelope bins when zoomed out; smoothing affects only the visual envelope. Raw PCM, FFT and descriptor measurements remain unchanged.',
  ),
  AnalysisTool(
    'spectrogram',
    'Signal',
    'Spectrogram',
    'Time × frequency × energy',
    'dB relative to frame-transform magnitude',
    'w[n] = ½ − ½ cos(2πn / (N−1))\nXₘ[k] = Σₙ x[mH+n] w[n] exp(−i2πkn/N)\nfₖ = kfₛ/N; tₘ = (mH+N/2)/fₛ',
    'The Fourier transform asks a tiny orchestra of sinusoids how much each one resembles the sound. Sliding the window turns their answers into a map.',
    'Hann-window STFT, one-sided spectrum including Nyquist. Color shows 20 log₁₀(max(|X|, 10⁻¹²)). Resolution is fₛ/N; increasing N trades time precision for frequency precision. This is not a calibrated power spectral density.',
  ),
  AnalysisTool(
    'spectrum',
    'Signal',
    'Frame spectrum',
    'A frequency fingerprint at the cursor',
    'Hz / magnitude',
    'A[k] = |Xₘ[k]|\nfₖ = kfₛ / N',
    'Freeze time and ask which frequencies are in the room.',
    'The selected Hann-window frame supplies the spectrum. Magnitudes are unnormalized FFT magnitudes; leakage and finite window length limit interpretation. No pitch estimate is implied.',
  ),
  AnalysisTool(
    'cqt',
    'Signal',
    'CQT pitch classes',
    'ECQT · native sparse kernels',
    'relative pitch-class energy',
    'Q = 1 / (2^(1/12) − 1)\nfₖ = 65.406391 · 2^(k/12)\nNₖ = ceil(Q fₛ / fₖ)\nC[k] = Σₙ x[n] wₖ[n] exp(−i2πQn/Nₖ) / Nₖ\nP[c] = Σₖ≡c (mod 12) |C[k]|² / Σₖ |C[k]|²',
    'Each note gets its own measuring cup: long windows for bass, short windows for treble. Fold the octaves together and the twelve pitch classes emerge.',
    'Native ECQT with PFFFT, Hamming kernels, 12 bins per octave from C2, sparse threshold 0.001, 22050 Hz mono. Pitch results update at 10 Hz and are held between updates. This is pitch-class energy, not a monophonic fundamental-frequency detector; harmonics can activate several classes. Silence returns zero. All kernels are centered on the cursor; lower pitches have longer windows and therefore blur transients more. The longest window is centered on the cursor and zero-padded at recording edges.',
  ),
  AnalysisTool(
    'rms',
    'Descriptors',
    'RMS energy',
    'Level without sign cancellation',
    'amplitude',
    'RMSₘ = √(Σₙ x[mH+n]² / N)\nLₘ = 20 log₁₀(max(RMSₘ, 10⁻¹²))',
    'Positive and negative waves cancel in a mean. Squaring lets both sides pay their energy bill.',
    'Computed on the unwindowed frame. RMS is an amplitude statistic, not perceptual loudness or SPL. Digital silence has RMS zero; its logarithm is floored.',
  ),
  AnalysisTool(
    'centroid',
    'Descriptors',
    'Spectral centroid',
    'The spectrum’s center of gravity',
    'Hz',
    'cₘ = Σₖ fₖ Aₘ[k] / Σₖ Aₘ[k]',
    'Imagine balancing the spectrum on a finger: the balance point often tracks brightness.',
    'Magnitude-weighted, including DC. Silence returns zero by convention; zero is not a meaningful brightness measurement. Brightness also depends on context and hearing.',
  ),
  AnalysisTool(
    'spread',
    'Descriptors',
    'Spectral spread',
    'Width around the spectral center',
    'Hz',
    'sₘ = √(Σₖ (fₖ−cₘ)² Aₘ[k] / Σₖ Aₘ[k])',
    'Two sounds can share a center of gravity while one spreads its energy across a much wider neighborhood.',
    'Magnitude-weighted standard deviation around the centroid. Silence returns zero. It measures spectral dispersion, not uncertainty of the centroid estimate.',
  ),
  AnalysisTool(
    'entropy',
    'Descriptors',
    'Spectral entropy',
    'How evenly power is distributed',
    'normalized [0, 1]',
    'pₖ = |X[k]|² / Σⱼ |X[j]|²\nE = −Σₖ pₖ ln(pₖ) / ln(K)',
    'A single strong frequency is predictable. A spread-out spectrum keeps you guessing.',
    'Uses one-sided power probabilities and 0 ln 0 = 0. Silence returns zero by convention. A high value does not establish musical complexity or randomness.',
  ),
  AnalysisTool(
    'flatness',
    'Descriptors',
    'Spectral flatness',
    'Tone-like versus noise-like spectra',
    'ratio [0, 1]',
    'F = exp(Σₖ ln(max(Pₖ, ε)) / K) / (Σₖ Pₖ / K)\nPₖ = |X[k]|²; ε = 10⁻²⁴',
    'The geometric mean punishes empty bins. A spectrum with power everywhere looks flatter than one with a few tall peaks.',
    'Power-based flatness. Silence returns zero. Flooring keeps logarithms finite and influences very quiet signals; flatness is not a categorical noise detector.',
  ),
  AnalysisTool(
    'rolloff',
    'Descriptors',
    '85% roll-off',
    'A spectral energy frontier',
    'Hz',
    'r = min fₖ such that Σⱼ≤ₖ Pⱼ ≥ 0.85 Σⱼ Pⱼ',
    'Walk up the frequency axis until you have collected 85% of the power.',
    'Uses power, not magnitude. Quantized to FFT bins. Silence returns zero. The 85% threshold is a descriptive convention, not a physical boundary.',
  ),
  AnalysisTool(
    'flux',
    'Descriptors',
    'Spectral flux',
    'Positive spectral change',
    'normalized magnitude change',
    'aₘ[k] = Aₘ[k] / Σⱼ Aₘ[j]\nFluxₘ = √Σₖ max(0, aₘ[k]−aₘ₋₁[k])²',
    'Listen for new arrivals in the spectrum rather than departures. Sharp arrivals often accompany attacks.',
    'Half-wave rectified change of L1-normalized magnitude spectra. First frame is zero. Silence-to-sound can create a peak; flux is not a verified onset annotation.',
  ),
  AnalysisTool(
    'zcr',
    'Descriptors',
    'Zero-crossing rate',
    'How often the waveform changes sign',
    'crossings / sample',
    'Z = Σₙ₌₁ᴺ⁻¹ 1[(x[n] ≥ 0) ≠ (x[n−1] ≥ 0)] / (N−1)',
    'Count how often the waveform crosses the street from positive to negative.',
    'Zero belongs to the nonnegative side. Unwindowed samples; DC offset and low-level noise affect the result. This is not a pitch detector.',
  ),
  AnalysisTool(
    'chroma',
    'Descriptors',
    'Chroma',
    'Energy folded into twelve pitch classes',
    'normalized pitch-class magnitude',
    'qₖ = round(69 + 12 log₂(fₖ/440))\nC[q mod 12] += A[k]; C ← C / Σ C',
    'Fold every octave onto the same twelve-note clock. A low C and a high C meet at midnight.',
    'FFT bins between 27.5 and 4186 Hz are assigned to equal-tempered pitch classes with A4 = 440 Hz. Coarse low-frequency bins limit accuracy. Chroma is not chord transcription.',
  ),
  AnalysisTool(
    'mfcc',
    'Descriptors',
    'MFCC',
    'Five coordinates of spectral envelope',
    'cepstral coefficients',
    'mel(f) = 2595 log₁₀(1+f/700)\nEᵦ = Σₖ P[k] Bᵦ[k]\ncⱼ = Σᵦ ln(max(Eᵦ, ε)) cos(πj(b+½)/B)',
    'Blur the spectrum through a mel-spaced filterbank, take logs, then compress its broad shape into a handful of numbers.',
    '26 triangular mel filters; five unnormalized DCT-II coefficients c₀…c₄. No pre-emphasis or liftering. c₀ includes level. Silence uses the log floor; coefficients depend on these conventions.',
  ),
  AnalysisTool(
    'beats',
    'Structure',
    'Beat tracking',
    'Causal PLP · pulse and beat events',
    'pulse / seconds',
    'Fₙ(ω) = Σₘ≤ₙ Δ[m] W[m−n] exp(−i2πωm)\nτₙ = argmax |Fₙ(τ/60)|; φₙ = −arg Fₙ / 2π\nκₙ(t) = W[t−n] cos(2π(τₙt/60−φₙ))\nΓₙ(t) = Σₗ≤ₙ κₗ(t) / Σ W',
    'Each onset votes for a little rhythmic pendulum. Pendulums that agree reinforce one another; their future swings predict the next beat.',
    'Independent implementation of causal PLP equations 8–9, Meier, Chiu & Müller (2024), doi:10.5334/tismir.189. Uses spectral-flux activation rather than the paper’s trained RNN. Signed pulse kernels are overlap-added; a local maximum at the lookahead decision line triggers a beat above the stability threshold. Frame times refer to the end of the audio window, so no future samples are used. Lookahead predicts rather than measures future beats. Audio capture, frame buffering and display introduce latency; zero device latency and the paper’s accuracy are not claimed. Half/double tempo ambiguity and weak onsets remain possible.',
  ),
  AnalysisTool(
    'tempo',
    'Descriptors',
    'Tempo candidates',
    'Periodicities in onset flux',
    'BPM / normalized autocorrelation',
    'R[ℓ] = Σₘ Fluxₘ Fluxₘ₊ℓ / Σₘ Fluxₘ²\nBPM(ℓ) = 60 fₛ / (Hℓ)',
    'Echo the attack envelope against itself. Repeating pulses line up at useful delays.',
    'Searches lags corresponding to 40–240 BPM. Half/double tempo ambiguity remains. Short or nonperiodic recordings may yield no reliable tempo; scores are not probabilities.',
  ),
  AnalysisTool(
    'correlation',
    'Statistics',
    'Correlation matrix',
    'Which descriptors move together?',
    'Pearson r [−1, 1]',
    'rᵢⱼ = Σₘ (xₘᵢ−μᵢ)(xₘⱼ−μⱼ) / √(Σₘ(xₘᵢ−μᵢ)² Σₘ(xₘⱼ−μⱼ)²)',
    'A duet of rising and falling measurements can reveal shared behavior. It cannot tell you who leads.',
    'RMS, centroid, spread, entropy, flatness, roll-off, flux and ZCR across all frames. Constant columns produce zero correlations, including their diagonal. Temporal dependence means frames are not independent observations; correlation is not causation.',
  ),
  AnalysisTool(
    'pca',
    'Statistics',
    'Principal components',
    'A two-axis map of descriptor variation',
    'standardized component scores',
    'Zₘⱼ = (xₘⱼ−μⱼ) / σⱼ\nR = ZᵀZ / (M−1)\nRv = λv; scores = Zv\nexplained fraction = λ / tr(R)',
    'Rotate the descriptor cloud until the widest directions become your axes. The axes are mixtures, not hidden musical labels.',
    'Standardized eight-descriptor PCA, sample standard deviation, symmetric Jacobi eigensolver. Constant columns become zero. Signs are arbitrary. Loadings and explained variance accompany the plot; no inference or clustering is implied.',
  ),
  AnalysisTool(
    'summary',
    'Statistics',
    'Interval summary',
    'Distribution inside the selected range',
    'descriptor-specific',
    'μ = Σₘ xₘ/M\ns = √(Σₘ(xₘ−μ)²/(M−1))\nhᵦ = count{xₘ in bin b}',
    'Averages are only one character in the story. The histogram shows the cast.',
    'Uses frame centers within the selected interval. Reports mean, sample standard deviation, minimum and maximum for each descriptor; histogram shows RMS. Empty intervals are reported explicitly. Overlapping frames are dependent.',
  ),
  AnalysisTool(
    'similarity',
    'Structure',
    'Self-similarity',
    'When does the recording resemble itself?',
    'cosine similarity [0, 1]',
    'Sᵢⱼ = Cᵢ · Cⱼ / (‖Cᵢ‖ ‖Cⱼ‖)',
    'Hold a mirror across time. Repeated musical material can leave bright blocks away from the diagonal.',
    'Cosine similarity of chroma vectors; silence pairs return zero. Up to 160 uniformly sampled frames bound memory. Shared pitch classes need not imply shared sections.',
  ),
  AnalysisTool(
    'novelty',
    'Structure',
    'Novelty & boundaries',
    'Changes in local recurrence',
    'positive checkerboard contrast',
    'ν(t) = max(0, mean(S before,before)+mean(S after,after)−2 mean(S before,after))',
    'A boundary looks like two neighborhoods that each agree internally but disagree with one another.',
    'A four-frame neighborhood on the downsampled similarity grid. Candidate local peaks exceed mean plus one standard deviation and are separated by at least one second. Endpoints lack full neighborhoods. Boundaries are suggestions; annotations are manual.',
  ),
  AnalysisTool(
    'frame',
    'Inspector',
    'Selected frame',
    'Measurements, units and analysis settings',
    'frame-specific',
    'm = argminⱼ |tⱼ − t_cursor|\ntⱼ = (jH+N/2)/fₛ',
    'The cursor is a microscope: every view should tell the same story about the same moment.',
    'Selects the nearest frame center. Edge frames are zero padded. Frame descriptors use the conventions documented by their individual Maths panels; silence-derived spectral values are placeholders.',
  ),
  AnalysisTool(
    'gain',
    'Experiments',
    'Paired gain experiment',
    'Level response versus spectral invariance',
    'gain / amplitude / residual',
    'y[n] = g x[n]\nRMS(y) = |g| RMS(x)\nΔL = 20 log₁₀|g|\nc(y) = c(x), for g ≠ 0',
    'Turn the same sound up without changing its shape. Energy should move; scale-invariant spectral descriptors should stay put.',
    'Reanalyzes the selected interval after floating-point gain, without clipping or playback. Reports measured and predicted RMS plus descriptor differences. Digital playback would clip values above full scale. Log floors and silence limit invariance; this is a within-recording experiment.',
  ),
];
const sections = [
  'Signal',
  'Descriptors',
  'Statistics',
  'Structure',
  'Inspector',
  'Experiments',
];
